const ActionType = {
  ADDQUIZ: "ADDQUIZ",
  TOGGLEACTIVE: "TOGGLEACTIVE",
  DELETQUIZ: "DELETQUIZ",
  PLAYQUIZ: "PLAYQUIZ",
  GETNAME: "GETNAME",
  GETANSWER: "GETANSWER",
  RESET: "RESET",
};

export default ActionType;
